version: '3'

services:
  # Streamlit service
  streamlit:
    build: .
    ports:
      - "8501:8501" # Expose Streamlit's default port
    depends_on:
      - prometheus
    volumes:
      - .:/app # Mount current directory to /app in the container
    environment:
      - STREAMLIT_SERVER_PORT=8501 # Ensure Streamlit runs on port 8501

  # Prometheus service
  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount the configuration file
    ports:
      - "8000:8000" # Expose Prometheus metrics on port 8000
    restart: always

  # Grafana service
  grafana:
    image: grafana/grafana:8.4.3
    ports:
      - "3000:3000" # Expose Grafana dashboard on port 3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Set Grafana admin password
    restart: always
